# Generated by Django 2.2.5 on 2020-03-11 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('name_ru', models.CharField(default='', max_length=255)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('point', models.CharField(default='', max_length=20)),
                ('categories', models.ManyToManyField(blank=True, null=True, related_name='childs', to='passport_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('point', models.CharField(default='', max_length=10)),
                ('descr', models.CharField(default='', max_length=255)),
                ('name_ru', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passport_app.District')),
            ],
        ),
        migrations.CreateModel(
            name='NotLoginUserVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('name_ru', models.CharField(default='', max_length=255, unique=True)),
                ('is_load_file', models.BooleanField(blank=True, default=False)),
                ('is_comment', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParserParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('name_ru', models.CharField(default='', max_length=255)),
                ('parser_parameter_type', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('name_ru', models.CharField(default='', max_length=255, unique=True)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SearchConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_phone_field', models.BooleanField(default=False)),
                ('show_email_field', models.BooleanField(default=False)),
                ('show_search_form_field', models.BooleanField(default=False)),
                ('show_owner_field', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfLocality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfRealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('title_rus', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfStreet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('name_ru', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_visit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('creator_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('name_ru', models.CharField(default='', max_length=255, unique=True)),
                ('value_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport_app.TypeOfValue')),
            ],
        ),
        migrations.CreateModel(
            name='SubtypeOfRealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('title_rus', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='passport_app.TypeOfRealEstate')),
            ],
        ),
        migrations.CreateModel(
            name='SubsubtypeOfRealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('title_rus', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtype', to='passport_app.SubtypeOfRealEstate')),
            ],
        ),
        migrations.CreateModel(
            name='SubsubsubtypeOfRealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('title_rus', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('subsubtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubtype', to='passport_app.SubsubtypeOfRealEstate')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passport_app.Locality')),
                ('type_of_street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport_app.TypeOfLocality')),
            ],
        ),
        migrations.CreateModel(
            name='SearchForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.TextField(default='')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('name_ru', models.CharField(default='', max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, null=True, to='passport_app.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passport_app.Country')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('house_number', models.CharField(default='', max_length=5)),
                ('korpus_number', models.CharField(default='', max_length=5)),
                ('building_number', models.CharField(default='', max_length=5)),
                ('flat_number', models.IntegerField(default=0)),
                ('kadastr_number', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=255)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('country_name', models.CharField(default='', max_length=255)),
                ('region_name', models.CharField(default='', max_length=255)),
                ('district_name', models.CharField(default='', max_length=255)),
                ('locality_name', models.CharField(default='', max_length=255)),
                ('street_name', models.CharField(default='', max_length=255)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('report_number', models.IntegerField(default=0)),
                ('categories', models.ManyToManyField(to='passport_app.Category')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passport_app.Country')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passport_app.District')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passport_app.Locality')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport_app.Owner')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passport_app.Region')),
                ('search_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passport_app.SearchForm')),
                ('street', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passport_app.Street')),
                ('subsubtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passport_app.SubsubtypeOfRealEstate')),
                ('subtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passport_app.SubtypeOfRealEstate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('name_ru', models.CharField(default='', max_length=255, unique=True)),
                ('url', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('login', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('password', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('authkey', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='passport_app.Priority')),
            ],
        ),
        migrations.CreateModel(
            name='ParserParameterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(default='')),
                ('parser_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport_app.ParserParameter')),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport_app.RealEstate')),
            ],
        ),
        migrations.AddField(
            model_name='parserparameter',
            name='parser_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passport_app.ParserType'),
        ),
        migrations.CreateModel(
            name='ParameterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(default='')),
                ('rate', models.FloatField(default=0.0)),
                ('comment', models.CharField(default='', max_length=255)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport_app.Parameter')),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport_app.RealEstate')),
            ],
        ),
        migrations.AddField(
            model_name='parameter',
            name='parser_parameters',
            field=models.ManyToManyField(blank=True, to='passport_app.ParserParameter'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passport_app.Unit'),
        ),
        migrations.AddField(
            model_name='locality',
            name='type_of_locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport_app.TypeOfLocality'),
        ),
        migrations.CreateModel(
            name='GroupVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_count', models.IntegerField(default=0)),
                ('day_period', models.IntegerField(default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='FormulaParameterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_label', models.CharField(default='', max_length=15, unique=True)),
                ('value', models.CharField(default='', max_length=255)),
                ('rate_label', models.CharField(default='', max_length=15, unique=True)),
                ('rate', models.CharField(default='', max_length=255)),
                ('formula_label', models.CharField(default='', max_length=15, unique=True)),
                ('formula', models.CharField(default='', max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport_app.Category')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport_app.Parameter')),
            ],
        ),
        migrations.CreateModel(
            name='FormulaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_label', models.CharField(default='', max_length=15, unique=True)),
                ('value', models.CharField(default='', max_length=255)),
                ('rate_label', models.CharField(default='', max_length=15, unique=True)),
                ('rate', models.CharField(default='', max_length=255)),
                ('formula_lbl', models.CharField(default='', max_length=15, unique=True)),
                ('formula', models.CharField(default='', max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('title_rus', models.CharField(max_length=255)),
                ('point', models.CharField(default='', max_length=20)),
                ('parser_type', models.IntegerField(default=0)),
                ('classifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifier', to='passport_app.Classifier')),
                ('type_of_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passport_app.TypeOfValue')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passport_app.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passport_app.Region'),
        ),
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(default='')),
                ('rate', models.FloatField(default=0.0)),
                ('validity', models.BooleanField(default=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field', to='passport_app.Field')),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport_app.RealEstate')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='parameters',
            field=models.ManyToManyField(blank=True, null=True, to='passport_app.Parameter'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='parent', to='passport_app.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
