# Generated by Django 2.2.5 on 2020-05-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
