# Generated by Django 2.2.5 on 2020-05-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_app', '0002_auto_20200509_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='inn',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
