# Generated by Django 2.2.5 on 2020-05-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passport_app', '0003_owner_inn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulacategory',
            old_name='value',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='formulacategory',
            name='formula_lbl',
        ),
        migrations.RemoveField(
            model_name='formulacategory',
            name='rate_label',
        ),
        migrations.RemoveField(
            model_name='formulacategory',
            name='value_label',
        ),
    ]
