# Generated by Django 2.2.5 on 2020-05-27 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passport_app', '0004_auto_20200525_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateClassifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_rate', models.FloatField()),
                ('max_rate', models.FloatField()),
                ('label', models.CharField(max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport_app.Category')),
            ],
        ),
    ]
