# Generated by Django 2.2.5 on 2020-06-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_app', '0007_auto_20200603_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchform',
            name='formula',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='searchform',
            name='formula_amount',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='searchform',
            name='formula_rate',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
