# Generated by Django 2.2.5 on 2020-06-08 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passport_app', '0008_auto_20200603_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulacategory',
            name='search_form',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='passport_app.SearchForm'),
            preserve_default=False,
        ),
    ]
